In [3]:
import numpy as np

In [2]:
from numpy import random

In [3]:
#輸入np array
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('資料型態',data.dtype)

資料型態 int64


In [4]:
#輸入計算出array維度與元素數量
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('維度',data.ndim)
print('元素數量',data.size)

維度 1
元素數量 10


In [5]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('data*2',data*2)
print('乘法運算：',np.array([1,2,3,4,5,6,7,8,9,9]*np.array([10,9,8,7,6,5,4,3,2,1])))
print('連乘：',data**2)
print('除法：',np.array([1,2,3,4,5,6,7,8,9,9]/np.array([10,9,8,7,6,5,4,3,2,1])))

data*2 [18  4  6  8 20 12 14 16  2 10]
乘法運算： [10 18 24 28 30 30 28 24 18  9]
連乘： [ 81   4   9  16 100  36  49  64   1  25]
除法： [0.1        0.22222222 0.375      0.57142857 0.83333333 1.2
 1.75       2.66666667 4.5        9.        ]


In [17]:
#array值排序
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('原本的值：',data)
data = np.sort(data)
print('小到大的排序：',data)
data = -np.sort(-data)
print('大到小的排序：',data)

原本的值： [ 9  2  3  4 10  6  7  8  1  5]
小到大的排序： [ 1  2  3  4  5  6  7  8  9 10]
大到小的排序： [10  9  8  7  6  5  4  3  2  1]


In [25]:
#array最小值、最大值、總和、累積和、累積比例
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('最小值',data.min())
print('最大值：',data.max())
print('總和：',data.sum())
print('累積和：',data.cumsum())
print('累積比例：',data.cumsum()/data.sum())

最小值 1
最大值： 10
總和： 55
累積和： [ 9 11 14 18 28 34 41 49 50 55]
累積比例： [0.16363636 0.2        0.25454545 0.32727273 0.50909091 0.61818182
 0.74545455 0.89090909 0.90909091 1.        ]


In [10]:
#產生亂數
import numpy.random as random

#指定隨機種子
np.random.seed(0)
#產生常態分佈（平均為0，標準差為1)的10個亂數
rnd_data = np.random.randn(10)
print('含有10個亂數的陣列:', rnd_data)

含有10個亂數的陣列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [29]:
#顯示到小數點後第三位
%precision 3

'%.3f'

In [30]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

# 隨機取出
# 取出10個(允許重複，放回抽樣)
print(random.choice(data, 10))
#  取出10個(不允許重複，不放回抽樣)
print(random.choice(data, 10, replace = False)) 

[10  4  3  3  1  6  9  9  7  9]
[10  9  4  5  3  2  7  1  8  6]


In [33]:
#產生矩陣
array1 = np.arange(9)
print(array1)
array2 = np.arange(9).reshape(3,3)
print(array2)
#第一列
print('第一列',array2[0,:])
#第一行
print('第一行',array2[:,0])

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
第一列 [0 1 2]
第一行 [0 3 6]


In [37]:
#矩陣運算
array1 = np.arange(9).reshape(3,3)
array2 = np.arange(9,18).reshape(3,3)
print('array1:',array1)
print('array2:',array2)
print('矩陣乘法：',np.dot(array1, array2))
print('元素之積：',array1 * array2)

array1: [[0 1 2]
 [3 4 5]
 [6 7 8]]
array2: [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
矩陣乘法： [[ 42  45  48]
 [150 162 174]
 [258 279 300]]
元素之積： [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [47]:
#製作元素為0或1的矩陣
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
