In [1]:
#import package
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn import ensemble, metrics
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
import math

In [9]:
# 開啟 CSV 檔案
dataset = pd.read_csv('train.csv')
testset = pd.read_csv('test.csv')

In [10]:
#將dataset shuffle
dataset = shuffle(dataset)
label = dataset.label
dataset = dataset[dataset.columns[:449]]

In [11]:
# s1061443_李杰穎
#svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

#10-fold cross-validation
kfold = KFold(10, True)
predicted = []
expected = []

#訓練模型
for train, test in kfold.split(dataset):
    X_train = dataset.iloc[train]
    Y_train = label.iloc[train]
    X_test = dataset.iloc[test]
    Y_test = label.iloc[test]
    svm = OneVsRestClassifier(SVC(gamma='scale')).fit(X_train, Y_train)
    expected.extend(Y_test)
    predicted.extend(svm.predict(X_test))


/usr/local/lib/python3.9/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass shuffle=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [12]:
print("Macro-average: {0}".format(metrics.f1_score(expected,predicted,average='macro')))
print("Micro-average: {0}".format(metrics.f1_score(expected,predicted,average='micro')))
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

print("Average = macro")
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='macro'))

print("\n")
print("Average = micro")
print('precision:', metrics.precision_score(expected, predicted, average='micro')) 
print('recall:',metrics.recall_score(expected, predicted,average='micro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='micro'))

print("\n")
print("Average = weighted")
print('precision:', metrics.precision_score(expected, predicted, average='weighted'))
print('recall:',metrics.recall_score(expected, predicted,average='micro'))
print('F1-score:',metrics.f1_score(expected,predicted,labels=[1,2,3,4],average='weighted'))

Macro-average: 0.9704003737173454
Micro-average: 0.9712808730614589
              precision    recall  f1-score   support

           0       1.00      0.95      0.98       145
           1       0.93      0.91      0.92       207
           2       1.00      0.96      0.98       119
           3       0.90      0.95      0.93       238
           4       0.97      0.99      0.98       256
           5       1.00      1.00      1.00       264
           6       1.00      0.99      1.00       240
           7       0.99      0.99      0.99       272

    accuracy                           0.97      1741
   macro avg       0.97      0.97      0.97      1741
weighted avg       0.97      0.97      0.97      1741

[[138   1   0   0   6   0   0   0]
 [  0 188   0  19   0   0   0   0]
 [  0   0 114   5   0   0   0   0]
 [  0  11   0 227   0   0   0   0]
 [  0   0   0   0 254   0   0   2]
 [  0   0   0   0   0 264   0   0]
 [  0   1   0   1   0   0 238   0]
 [  0   1   0   0   3   0   0 268]]
