# Numpy

In [3]:
import numpy as np

## Q1

In [12]:
# 1061443_李杰穎
'''
data = np.array([1,2,3,4,5,6,7,8,9,10,
                11,12,13,14,15,16,17,18,19,20,
                21,22,23,24,25,26,27,28,29,30,
                31,32,33,34,35,36,37,38,39,40,
                41,42,43,44,45,46,47,48,49,50])
data.sum()                
'''

1275

## Q2

In [7]:
# 1061443_李杰穎
'''
np.random.seed(0)
rnd_data = np.random.randn(10)
print('最小值：', rnd_data.min())
print('最大值：', rnd_data.max())
print('總和：', rnd_data.sum())
'''

最小值： -0.977277879876411
最大值： 2.240893199201458
總和： 7.380231707288347


## Q3

In [33]:
# 1061443_李杰穎
'''
data = np.ones((25), dtype = np.int64)*3
data = data.reshape(5, 5)
print(np.dot(data, data))
'''

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]


## Q4

In [46]:
# 1061443_李杰穎
'''
%precision 3
np.random.seed(1)
array1 = np.random.randn(16).reshape(4, 4)
print('array1:\n', array1)
np.random.seed(2)
array2 = np.random.randn(16).reshape(4, 4)
print('array2:\n', array2)
print('array1*array2:\n', array1*array2)
print('array1dotarray2:\n', np.dot(array1, array2))
'''

array1:
 [[ 1.624 -0.612 -0.528 -1.073]
 [ 0.865 -2.302  1.745 -0.761]
 [ 0.319 -0.249  1.462 -2.06 ]
 [-0.322 -0.384  1.134 -1.1  ]]
array2:
 [[-0.417 -0.056 -2.136  1.64 ]
 [-1.793 -0.842  0.503 -1.245]
 [-1.058 -0.909  0.551  2.292]
 [ 0.042 -1.118  0.539 -0.596]]
array1*array2:
 [[-0.677  0.034  1.128 -1.76 ]
 [-1.552  1.937  0.877  0.948]
 [-0.338  0.227  0.806 -4.722]
 [-0.013  0.429  0.611  0.656]]
array1dotarray2:
 [[ 0.934  2.103 -4.647  2.855]
 [ 1.889  1.154 -2.454  8.739]
 [-1.318  1.166 -1.111  5.413]
 [-0.422  0.54   0.528  3.204]]


# Pandas

In [47]:
# 1061443_李杰穎
from pandas import Series,DataFrame
import pandas as pd

attri_data1 = {'ID':['1','2','3','4','5'],
               'Sex':['F','F','M','M','F'],
               'Money':[1000,2000,500,300,700],
               'Name':['Alice','Bob','Candy','David','Ella']}

attri_data_frame1 = DataFrame(attri_data1)
attri_data_frame1

ID Sex  Money   Name
0  1   F   1000  Alice
1  2   F   2000    Bob
2  3   M    500  Candy
3  4   M    300  David
4  5   F    700   Ella

## Q1

In [48]:
# 1061443_李杰穎
'''
attri_data_frame1[attri_data_frame1['Money'] >= 500]
'''

ID Sex  Money   Name
0  1   F   1000  Alice
1  2   F   2000    Bob
2  3   M    500  Candy
4  5   F    700   Ella

## Q2

In [49]:
# 1061443_李杰穎
'''
attri_data_frame1.groupby('Sex')['Money'].mean()
'''

Sex
F    1233.333333
M     400.000000
Name: Money, dtype: float64

In [50]:
attri_data2 = {'ID':['3','4','7'],
               'Math':[60,30,40],
               'English':[80,20,30]}

attri_data_frame2 = DataFrame(attri_data2)
attri_data_frame2

ID  Math  English
0  3    60       80
1  4    30       20
2  7    40       30

## Q3

In [51]:
# 1061443_李杰穎
'''
attri_data_frame3 = pd.merge(attri_data_frame1, attri_data_frame2)
attri_data_frame3
'''

ID Sex  Money   Name  Math  English
0  3   M    500  Candy    60       80
1  4   M    300  David    30       20

## Q4

In [52]:
# 1061443_李杰穎
'''
attri_data_frame3.mean()
'''

ID          17.0
Money      400.0
Math        45.0
English     50.0
dtype: float64

# Pandas Advanced

In [79]:
id_arr = np.arange(1, 101)
id_arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [63]:
np.random.seed(2)
array2 = np.random.randint(2, size=100)
sex = []
for i in array2:
    if i == 0: sex.append('F') 
    else: sex.append('M')
print(sex)

['F', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'F', 'F', 'F', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'M', 'F', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'F']


In [67]:
np.random.seed(3)
money = np.random.normal(1000, 10, size=100)
print(money)

[1017.886 1004.365 1000.965  981.365  997.226  996.452  999.173  993.73
  999.562  995.228  986.861 1008.846 1008.813 1017.096 1000.5    995.953
  994.546  984.535 1009.824  988.989  988.15   997.944 1014.861 1002.367
  989.762  992.87  1006.252  998.395  992.312  997.7   1007.451 1019.761
  987.559  993.736  991.962  975.809  990.762  989.761 1011.24   998.681
  983.767 1006.467  996.437  982.569  994.034  994.114  991.261 1000.297
  977.517  997.322 1010.132 1008.528 1011.082 1011.194 1014.875  988.817
 1008.458  981.391  993.971  980.855 1010.481 1013.337  998.026 1017.746
  993.253 1001.506 1001.529  989.358 1004.379 1019.39   989.751 1008.993
  998.455 1017.696 1004.838 1006.762 1006.432 1002.491  986.042 1013.917
  986.293 1002.386 1006.141  991.621 1001.451 1011.679  999.759  991.113
  970.843  990.282  994.089  994.836  990.4   1003.773  994.253  998.905
 1006.791  991.446  996.998 1021.581]


In [80]:
data = {
    'ID': id_arr,
    'Sex': sex,
    'Money': money,
}
data = DataFrame(data)
data

ID Sex        Money
0     1   F  1017.886285
1     2   M  1004.365099
2     3   M  1000.964975
3     4   F   981.365073
4     5   F   997.226118
..  ...  ..          ...
95   96   M   998.905457
96   97   F  1006.790716
97   98   M   991.445628
98   99   F   996.997939
99  100   F  1021.581493

[100 rows x 3 columns]

## Q1

In [90]:
# 1061443_李杰穎
'''
data[data['Money'] == data['Money'].min()]
'''

ID Sex       Money
88  89   F  970.842622

## Q2

In [85]:
# 1061443_李杰穎
'''
data[data['Money'] > 1010]
'''

ID Sex        Money
0     1   F  1017.886285
13   14   M  1017.095731
22   23   M  1014.861484
31   32   F  1019.761108
38   39   M  1011.239780
50   51   F  1010.131834
52   53   F  1011.081875
53   54   F  1011.193907
54   55   F  1014.875431
60   61   F  1010.481475
61   62   F  1013.337378
63   64   M  1017.746450
69   70   M  1019.389785
73   74   F  1017.696273
79   80   F  1013.916629
85   86   F  1011.678823
99  100   F  1021.581493

## Q3

In [92]:
# 1061443_李杰穎
'''
data[data['Money'] > 1010].sort_values(by='Money', ascending=False)
'''

ID Sex        Money
99  100   F  1021.581493
31   32   F  1019.761108
69   70   M  1019.389785
0     1   F  1017.886285
63   64   M  1017.746450
73   74   F  1017.696273
13   14   M  1017.095731
54   55   F  1014.875431
22   23   M  1014.861484
79   80   F  1013.916629
61   62   F  1013.337378
85   86   F  1011.678823
38   39   M  1011.239780
53   54   F  1011.193907
52   53   F  1011.081875
60   61   F  1010.481475
50   51   F  1010.131834

# Fillna

In [107]:
from numpy import nan as NA
np.random.seed(0)
df2 = pd.DataFrame(np.random.rand(15, 6))
df2.iloc[2,0] = NA
df2.iloc[5:8,2] = NA
df2.iloc[7:9,3] = NA
df2.iloc[10,5] = NA
df2

0         1         2         3         4         5
0   0.548814  0.715189  0.602763  0.544883  0.423655  0.645894
1   0.437587  0.891773  0.963663  0.383442  0.791725  0.528895
2        NaN  0.925597  0.071036  0.087129  0.020218  0.832620
3   0.778157  0.870012  0.978618  0.799159  0.461479  0.780529
4   0.118274  0.639921  0.143353  0.944669  0.521848  0.414662
5   0.264556  0.774234       NaN  0.568434  0.018790  0.617635
6   0.612096  0.616934       NaN  0.681820  0.359508  0.437032
7   0.697631  0.060225       NaN       NaN  0.210383  0.128926
8   0.315428  0.363711  0.570197       NaN  0.988374  0.102045
9   0.208877  0.161310  0.653108  0.253292  0.466311  0.244426
10  0.158970  0.110375  0.656330  0.138183  0.196582       NaN
11  0.820993  0.097101  0.837945  0.096098  0.976459  0.468651
12  0.976761  0.604846  0.739264  0.039188  0.282807  0.120197
13  0.296140  0.118728  0.317983  0.414263  0.064147  0.692472
14  0.566601  0.265389  0.523248  0.093941  0.575946  0.929296

## Q1

In [101]:
# 1061443_李杰穎
'''
df2.dropna()
'''

0         1         2         3         4         5
0   0.548814  0.715189  0.602763  0.544883  0.423655  0.645894
1   0.437587  0.891773  0.963663  0.383442  0.791725  0.528895
3   0.778157  0.870012  0.978618  0.799159  0.461479  0.780529
4   0.118274  0.639921  0.143353  0.944669  0.521848  0.414662
9   0.208877  0.161310  0.653108  0.253292  0.466311  0.244426
11  0.820993  0.097101  0.837945  0.096098  0.976459  0.468651
12  0.976761  0.604846  0.739264  0.039188  0.282807  0.120197
13  0.296140  0.118728  0.317983  0.414263  0.064147  0.692472
14  0.566601  0.265389  0.523248  0.093941  0.575946  0.929296

## Q2

In [103]:
# 1061443_李杰穎
'''
df2.fillna(0)
'''

0         1         2         3         4         5
0   0.548814  0.715189  0.602763  0.544883  0.423655  0.645894
1   0.437587  0.891773  0.963663  0.383442  0.791725  0.528895
2   0.000000  0.925597  0.071036  0.087129  0.020218  0.832620
3   0.778157  0.870012  0.978618  0.799159  0.461479  0.780529
4   0.118274  0.639921  0.143353  0.944669  0.521848  0.414662
5   0.264556  0.774234  0.000000  0.568434  0.018790  0.617635
6   0.612096  0.616934  0.000000  0.681820  0.359508  0.437032
7   0.697631  0.060225  0.000000  0.000000  0.210383  0.128926
8   0.315428  0.363711  0.570197  0.000000  0.988374  0.102045
9   0.208877  0.161310  0.653108  0.253292  0.466311  0.244426
10  0.158970  0.110375  0.656330  0.138183  0.196582  0.000000
11  0.820993  0.097101  0.837945  0.096098  0.976459  0.468651
12  0.976761  0.604846  0.739264  0.039188  0.282807  0.120197
13  0.296140  0.118728  0.317983  0.414263  0.064147  0.692472
14  0.566601  0.265389  0.523248  0.093941  0.575946  0.929296

## Q3

In [109]:
# 1061443_李杰穎
'''
df2[0] = df2[0].fillna(df2[0].mean())
df2[1] = df2[1].fillna(df2[1].mean())
df2[2] = df2[2].fillna(df2[2].mean())
df2[3] = df2[3].fillna(df2[3].mean())
df2[4] = df2[4].fillna(df2[4].mean())
df2[5] = df2[5].fillna(df2[5].mean())
df2
'''

0         1         2         3         4         5
0   0.548814  0.715189  0.602763  0.544883  0.423655  0.645894
1   0.437587  0.891773  0.963663  0.383442  0.791725  0.528895
2   0.485778  0.925597  0.071036  0.087129  0.020218  0.832620
3   0.778157  0.870012  0.978618  0.799159  0.461479  0.780529
4   0.118274  0.639921  0.143353  0.944669  0.521848  0.414662
5   0.264556  0.774234  0.588126  0.568434  0.018790  0.617635
6   0.612096  0.616934  0.588126  0.681820  0.359508  0.437032
7   0.697631  0.060225  0.588126  0.388038  0.210383  0.128926
8   0.315428  0.363711  0.570197  0.388038  0.988374  0.102045
9   0.208877  0.161310  0.653108  0.253292  0.466311  0.244426
10  0.158970  0.110375  0.656330  0.138183  0.196582  0.495949
11  0.820993  0.097101  0.837945  0.096098  0.976459  0.468651
12  0.976761  0.604846  0.739264  0.039188  0.282807  0.120197
13  0.296140  0.118728  0.317983  0.414263  0.064147  0.692472
14  0.566601  0.265389  0.523248  0.093941  0.575946  0.929296